import { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { createSalesforceOpportunity, loadSalesforceSalesPulseData, updateSalesforceOpportunity } from './data/salesforceGateway';
import type { Account, Opportunity, OpportunityInput } from './data/types';
import { mockAccounts, mockOpportunities } from './data/mockData';
import './styles/sales-pulse.css';

const money = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 });
const stages = ['Prospecting', 'Qualification', 'Needs Analysis', 'Value Proposition', 'Proposal/Price Quote', 'Negotiation/Review', 'Closed Won', 'Closed Lost'];

function App() {
  const [accounts, setAccounts] = useState<Account[]>(mockAccounts); const [opportunities, setOpportunities] = useState<Opportunity[]>(mockOpportunities); const [view, setView] = useState<'opportunities' | 'accounts'>('opportunities'); const [live, setLive] = useState(false); const [query, setQuery] = useState(''); const [notice, setNotice] = useState('Loading Salesforce records…'); const [editing, setEditing] = useState<Opportunity | null>(null); const [creating, setCreating] = useState(false); const [accountDetail, setAccountDetail] = useState<Account | null>(null);
  const refresh = async () => { const data = await loadSalesforceSalesPulseData(); setAccounts(data.accounts); setOpportunities(data.opportunities); setLive(true); };
  useEffect(() => { refresh().then(() => setNotice('Live Salesforce data loaded.')).catch(() => setNotice('Preview mode: open this app inside Salesforce to use live records.')); }, []);
  const accountName = (id: string) => accounts.find(a => a.id === id)?.name ?? 'Unassigned account';
  const visible = useMemo(() => opportunities.filter(o => `${o.name} ${accountName(o.accountId)} ${o.stageName}`.toLowerCase().includes(query.toLowerCase())), [opportunities, accounts, query]);
  const save = async (o: Opportunity, values: Pick<Opportunity, 'stageName' | 'amount' | 'closeDate' | 'nextStep'>) => { if (!live) return; try { await updateSalesforceOpportunity({ id: o.id, ...values }); await refresh(); setEditing(null); setNotice('Opportunity updated in Salesforce.'); } catch (e) { setNotice(`Save failed: ${e instanceof Error ? e.message : 'Unknown error'}`); } };
  const create = async (input: OpportunityInput) => { if (!live) return; try { await createSalesforceOpportunity(input); await refresh(); setCreating(false); setNotice('Opportunity created in Salesforce.'); } catch (e) { setNotice(`Create failed: ${e instanceof Error ? e.message : 'Unknown error'}`); } };
  const visibleAccounts = accounts.filter(a => `${a.name} ${a.industry} ${a.billingCity}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="sales-pulse-app"><aside className="side-rail"><div className="brand">Sales Pulse</div><nav className="nav-list"><button className={`nav-item ${view === 'opportunities' ? 'active' : ''}`} onClick={() => setView('opportunities')}>Opportunities</button><button className={`nav-item ${view === 'accounts' ? 'active' : ''}`} onClick={() => setView('accounts')}>Accounts</button></nav><div className="rail-bottom"><span className="live-dot" />{live ? 'Salesforce write mode' : 'Preview mode'}</div></aside><main><header className="topbar"><div className="breadcrumb"><b>Sales Pulse</b><span> / {view === 'accounts' ? 'Accounts' : 'Opportunities'}</span></div><div className="top-actions"><label className="command-search"><input value={query} onChange={e => setQuery(e.target.value)} placeholder={`Search ${view}`} /></label>{view === 'opportunities' && <button className="primary-button" onClick={() => setCreating(true)}>New opportunity</button>}</div></header>{notice && <div className="notice"><span>{notice}</span><button onClick={() => setNotice('')}>×</button></div>}<div className="page-shell">{view === 'opportunities' ? <OpportunityTable rows={visible} accountName={accountName} live={live} onOpen={setEditing} /> : <AccountTable accounts={visibleAccounts} opportunities={opportunities} onOpen={setAccountDetail} />}</div></main>{(editing || creating) && <OpportunityForm opportunity={editing} accounts={accounts} live={live} onClose={() => { setEditing(null); setCreating(false); }} onSave={save} onCreate={create} />}{accountDetail && <AccountModal account={accountDetail} opportunities={opportunities.filter(o => o.accountId === accountDetail.id)} onClose={() => setAccountDetail(null)} onOpenOpportunity={setEditing} />}</div>;
}

function OpportunityTable({ rows, accountName, live, onOpen }: { rows: Opportunity[]; accountName: (id: string) => string; live: boolean; onOpen: (o: Opportunity) => void }) { return <><section className="hero-row"><div><p className="eyebrow">SALESFORCE RECORD WORKSPACE</p><h1>Opportunity Register</h1><p className="hero-subtitle">Create and update Salesforce opportunities directly from this workspace.</p></div></section><section className="panel data-table-panel"><div className="table-toolbar"><div><h2>Opportunities</h2><span>{live ? `${rows.length} records available for update` : 'Live writes require Salesforce hosting'}</span></div></div><div className="responsive-table"><div className="table-head"><span>Opportunity</span><span>Account</span><span>Stage</span><span>Close date</span><span>Amount</span></div>{rows.map(o => <button className="table-row" key={o.id} onClick={() => onOpen(o)}><span className="table-account"><i>OP</i><span><b>{o.name}</b><small>{o.nextStep || 'No next step'}</small></span></span><span>{accountName(o.accountId)}</span><span>{o.stageName}</span><span>{o.closeDate}</span><strong>{money.format(o.amount)}</strong></button>)}</div></section></>; }

function AccountTable({ accounts, opportunities, onOpen }: { accounts: Account[]; opportunities: Opportunity[]; onOpen: (a: Account) => void }) { return <><section className="hero-row"><div><p className="eyebrow">SALESFORCE RECORD WORKSPACE</p><h1>Account Register</h1><p className="hero-subtitle">Select an account to review its profile and related pipeline.</p></div></section><section className="panel data-table-panel"><div className="table-toolbar"><div><h2>Accounts</h2><span>{accounts.length} accounts available</span></div></div><div className="responsive-table"><div className="table-head"><span>Account</span><span>Industry</span><span>Location</span><span>Open pipeline</span><span>Owner</span></div>{accounts.map(a => { const pipeline = opportunities.filter(o => o.accountId === a.id && !o.isClosed).reduce((n, o) => n + o.amount, 0); return <button className="table-row" key={a.id} onClick={() => onOpen(a)}><span className="table-account"><i>AC</i><span><b>{a.name}</b><small>{a.type || 'Account'}</small></span></span><span>{a.industry || '—'}</span><span>{[a.billingCity, a.billingState].filter(Boolean).join(', ') || '—'}</span><strong>{money.format(pipeline)}</strong><span>{a.owner.name}</span></button>; })}</div></section></>; }

function AccountModal({ account, opportunities, onClose, onOpenOpportunity }: { account: Account; opportunities: Opportunity[]; onClose: () => void; onOpenOpportunity: (o: Opportunity) => void }) { return <div className="modal-scrim"><section className="opportunity-modal"><header><div><p className="eyebrow">ACCOUNT DETAIL</p><h2>{account.name}</h2></div><button className="icon-button" onClick={onClose}>×</button></header><div className="form-grid"><Info label="Industry" value={account.industry} /><Info label="Owner" value={account.owner.name} /><Info label="Location" value={[account.billingCity, account.billingState].filter(Boolean).join(', ')} /><Info label="Phone" value={account.phone} /><div className="field field-wide"><span>Related opportunities</span>{opportunities.length ? opportunities.map(o => <button className="text-link" key={o.id} onClick={() => { onClose(); onOpenOpportunity(o); }}>{o.name} · {money.format(o.amount)}</button>) : <strong>None</strong>}</div></div><footer><span className="write-status">Account details are read-only</span><button className="secondary-button" onClick={onClose}>Close</button></footer></section></div>; }
function Info({ label, value }: { label: string; value?: string }) { return <div className="field"><span>{label}</span><strong>{value || '—'}</strong></div>; }

function OpportunityForm({ opportunity, accounts, live, onClose, onSave, onCreate }: { opportunity: Opportunity | null; accounts: Account[]; live: boolean; onClose: () => void; onSave: (o: Opportunity, values: Pick<Opportunity, 'stageName' | 'amount' | 'closeDate' | 'nextStep'>) => void; onCreate: (i: OpportunityInput) => void }) { const [name, setName] = useState(opportunity?.name ?? ''); const [accountId, setAccountId] = useState(opportunity?.accountId ?? accounts[0]?.id ?? ''); const [stageName, setStageName] = useState(opportunity?.stageName ?? stages[0]); const [amount, setAmount] = useState(opportunity?.amount ?? 0); const [closeDate, setCloseDate] = useState(opportunity?.closeDate ?? ''); const [nextStep, setNextStep] = useState(opportunity?.nextStep ?? ''); return <div className="modal-scrim"><form className="opportunity-modal" onSubmit={e => { e.preventDefault(); if (opportunity) onSave(opportunity, { stageName, amount: Number(amount), closeDate, nextStep }); else onCreate({ name, accountId, stageName, amount: Number(amount), probability: 0, closeDate, nextStep, type: '', leadSource: '', description: '' }); }}><header><div><p className="eyebrow">{opportunity ? 'EDIT OPPORTUNITY' : 'NEW OPPORTUNITY'}</p><h2>{opportunity ? opportunity.name : 'Create opportunity'}</h2></div><button type="button" className="icon-button" onClick={onClose}>×</button></header><div className="form-grid"><label className="field field-wide">Name<input required disabled={Boolean(opportunity)} value={name} onChange={e => setName(e.target.value)} /></label><label className="field">Account<select required disabled={Boolean(opportunity)} value={accountId} onChange={e => setAccountId(e.target.value)}>{accounts.map(a => <option value={a.id} key={a.id}>{a.name}</option>)}</select></label><label className="field">Stage<select value={stageName} onChange={e => setStageName(e.target.value)}>{stages.map(s => <option key={s}>{s}</option>)}</select></label><label className="field">Amount<input required type="number" min="0" value={amount} onChange={e => setAmount(Number(e.target.value))} /></label><label className="field">Close date<input required type="date" value={closeDate} onChange={e => setCloseDate(e.target.value)} /></label><label className="field field-wide">Next step<input value={nextStep} onChange={e => setNextStep(e.target.value)} /></label></div><footer><span className="write-status"><span className="live-dot" /> {live ? 'Salesforce write mode enabled' : 'Preview mode'}</span><div><button className="secondary-button" type="button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={!live}>{opportunity ? 'Save changes' : 'Create opportunity'}</button></div></footer></form></div>; }
createRoot(document.getElementById('root')!).render(<App />);
