import { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { createSalesforceOpportunity, loadSalesforceSalesPulseData, updateSalesforceOpportunity } from './data/salesforceGateway';
import type { Account, Opportunity, OpportunityInput } from './data/types';
import { mockAccounts, mockOpportunities } from './data/mockData';
import './styles/sales-pulse.css';

const money = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 });
const defaultStages = ['Prospecting', 'Qualification', 'Needs Analysis', 'Value Proposition', 'Proposal/Price Quote', 'Negotiation/Review', 'Closed Won', 'Closed Lost'];

function App() {
  const [accounts, setAccounts] = useState<Account[]>(mockAccounts);
  const [opportunities, setOpportunities] = useState<Opportunity[]>(mockOpportunities);
  const [live, setLive] = useState(false); const [notice, setNotice] = useState('Loading Salesforce records…');
  const [editing, setEditing] = useState<Opportunity | null>(null); const [creating, setCreating] = useState(false); const [query, setQuery] = useState('');
  const refresh = async () => { const data = await loadSalesforceSalesPulseData(); setAccounts(data.accounts); setOpportunities(data.opportunities); setLive(true); };
  useEffect(() => { refresh().then(() => setNotice('Live Salesforce data loaded.')).catch(() => setNotice('Preview mode: open this app inside Salesforce to use live records.')); }, []);
  const accountName = (id: string) => accounts.find(a => a.id === id)?.name ?? 'Unassigned account';
  const stages = useMemo(() => [...new Set([...defaultStages, ...opportunities.map(o => o.stageName)])], [opportunities]);
  const save = async (opportunity: Opportunity, values: Pick<Opportunity, 'stageName' | 'amount' | 'closeDate' | 'nextStep'>) => {
    if (!live) return;
    try { await updateSalesforceOpportunity({ id: opportunity.id, ...values }); await refresh(); setEditing(null); setNotice('Opportunity updated in Salesforce.'); } catch (e) { setNotice(`Save failed: ${e instanceof Error ? e.message : 'Unknown Salesforce error'}`); }
  };
  const create = async (input: OpportunityInput) => {
    if (!live) return;
    try { await createSalesforceOpportunity(input); await refresh(); setCreating(false); setNotice('Opportunity created in Salesforce.'); } catch (e) { setNotice(`Create failed: ${e instanceof Error ? e.message : 'Unknown Salesforce error'}`); }
  };
  const filtered = opportunities.filter(o => `${o.name} ${accountName(o.accountId)} ${o.stageName}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="sales-pulse-app"><aside className="side-rail"><div className="brand"><span>Sales Pulse</span></div><nav className="nav-list"><button className="nav-item active">Dashboard</button><button className="nav-item">Opportunities</button><button className="nav-item">Accounts</button></nav><div className="rail-bottom"><div className="demo-note"><span className="live-dot" />{live ? ' Salesforce write mode' : ' Preview mode'}</div></div></aside><main className="main-canvas"><header className="topbar"><div className="breadcrumb"><b>Sales Pulse</b><span> / Opportunity workspace</span></div><div className="top-actions"><label className="command-search"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search opportunities" /></label><button className="primary-button" onClick={() => setCreating(true)}>New opportunity</button></div></header>{notice && <div className="notice"><span>{notice}</span><button onClick={() => setNotice('')}>×</button></div>}<div className="page-shell"><section className="hero-row"><div><p className="eyebrow">SALESFORCE RECORD WORKSPACE</p><h1>Opportunity Register</h1><p className="hero-subtitle">Create and update Salesforce opportunities. Each action requires confirmation and follows your Salesforce permissions.</p></div></section><section className="panel data-table-panel"><div className="table-toolbar"><div><h2>Opportunities</h2><span>{live ? `${filtered.length} records available for update` : 'Live writes are available only inside Salesforce'}</span></div></div><div className="responsive-table"><div className="table-head"><span>Opportunity</span><span>Account</span><span>Stage</span><span>Close date</span><span>Amount</span></div>{filtered.map(o => <button className="table-row" key={o.id} onClick={() => setEditing(o)}><span className="table-account"><i>OP</i><span><b>{o.name}</b><small>{o.nextStep || 'No next step'}</small></span></span><span>{accountName(o.accountId)}</span><span>{o.stageName}</span><span>{o.closeDate}</span><strong>{money.format(o.amount)}</strong></button>)}</div></section></div></main>{(editing || creating) && <OpportunityForm opportunity={editing} accounts={accounts} stages={stages} live={live} onClose={() => { setEditing(null); setCreating(false); }} onSave={save} onCreate={create} />}</div>;
}

function OpportunityForm({ opportunity, accounts, stages, live, onClose, onSave, onCreate }: { opportunity: Opportunity | null; accounts: Account[]; stages: string[]; live: boolean; onClose: () => void; onSave: (o: Opportunity, v: Pick<Opportunity, 'stageName' | 'amount' | 'closeDate' | 'nextStep'>) => void; onCreate: (i: OpportunityInput) => void }) {
  const [name, setName] = useState(opportunity?.name ?? ''); const [accountId, setAccountId] = useState(opportunity?.accountId ?? accounts[0]?.id ?? ''); const [stageName, setStageName] = useState(opportunity?.stageName ?? stages[0]); const [amount, setAmount] = useState(opportunity?.amount ?? 0); const [closeDate, setCloseDate] = useState(opportunity?.closeDate ?? ''); const [nextStep, setNextStep] = useState(opportunity?.nextStep ?? '');
  return <div className="modal-scrim"><form className="opportunity-modal" onSubmit={e => { e.preventDefault(); if (opportunity) onSave(opportunity, { stageName, amount: Number(amount), closeDate, nextStep }); else onCreate({ name, accountId, stageName, amount: Number(amount), probability: 0, closeDate, nextStep, type: '', leadSource: '', description: '' }); }}><header><div><p className="eyebrow">{opportunity ? 'EDIT OPPORTUNITY' : 'NEW OPPORTUNITY'}</p><h2>{opportunity ? opportunity.name : 'Create opportunity'}</h2></div><button type="button" className="icon-button" onClick={onClose}>×</button></header><div className="form-grid"><label className="field field-wide">Name<input required disabled={Boolean(opportunity)} value={name} onChange={e => setName(e.target.value)} /></label><label className="field">Account<select required disabled={Boolean(opportunity)} value={accountId} onChange={e => setAccountId(e.target.value)}>{accounts.map(a => <option value={a.id} key={a.id}>{a.name}</option>)}</select></label><label className="field">Stage<select value={stageName} onChange={e => setStageName(e.target.value)}>{stages.map(s => <option key={s}>{s}</option>)}</select></label><label className="field">Amount<input required type="number" min="0" value={amount} onChange={e => setAmount(Number(e.target.value))} /></label><label className="field">Close date<input required type="date" value={closeDate} onChange={e => setCloseDate(e.target.value)} /></label><label className="field field-wide">Next step<input value={nextStep} onChange={e => setNextStep(e.target.value)} /></label></div><footer><span className="write-status"><span className="live-dot" /> {live ? 'Salesforce write mode enabled' : 'Preview mode'}</span><div><button className="secondary-button" type="button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={!live}>{opportunity ? 'Save changes' : 'Create opportunity'}</button></div></footer></form></div>;
}

createRoot(document.getElementById('root')!).render(<App />);
